CREATE TABLE "users" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_name" varchar NOT NULL,
  "user_email" varchar UNIQUE NOT NULL,
  "user_password" varchar NOT NULL,
  "user_age" int NOT NULL,
  "user_cate" int NOT NULL
);

CREATE TABLE "courses" (
  "cour_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cour_title" varchar NOT NULL,
  "cour_descrip" text NOT NULL,
  "cour_level" int NOT NULL,
  "cour_teacher" int NOT NULL,
  "cour_video" int NOT NULL
);

CREATE TABLE "course_videos" (
  "covi_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "covi_title" varchar NOT NULL,
  "covi_url" varchar NOT NULL
);

CREATE TABLE "categories" (
  "cate_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cate_name" varchar NOT NULL
);

CREATE TABLE "label" (
  "tabl_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tabl_descrip" varchar NOT NULL
);

CREATE TABLE "users_courses" (
  "uscu_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uscu_user" int NOT NULL,
  "uscu_cour" int NOT NULL
);

CREATE TABLE "teachers" (
  "teac_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "teac_name" varchar NOT NULL
);

ALTER TABLE "courses" ADD FOREIGN KEY ("cour_level") REFERENCES "label" ("tabl_id");

ALTER TABLE "courses" ADD FOREIGN KEY ("cour_video") REFERENCES "course_videos" ("covi_id");

ALTER TABLE "users_courses" ADD FOREIGN KEY ("uscu_user") REFERENCES "users" ("user_id");

ALTER TABLE "users_courses" ADD FOREIGN KEY ("uscu_cour") REFERENCES "courses" ("cour_id");

ALTER TABLE "users" ADD FOREIGN KEY ("user_cate") REFERENCES "categories" ("cate_id");

ALTER TABLE "courses" ADD FOREIGN KEY ("cour_teacher") REFERENCES "teachers" ("teac_id");



Insert into categories (cate_name)
values
('BECA'),
('MEDIA BECA'),
('REGULAR');

Insert into teachers(teac_name)
values
('JESÚS FERNÁNDEZ'),
('JUNIOR PACHECO'),
('SAHID KICK');

Insert into label(tabl_descrip)
values
('BASICO'),
('MEDIO'),
('AVANZADO');

Insert into course_videos(covi_title,covi_url )
values
('html, css javascript', 'https://academlo.notion.site/Generaci-n-22-G2-dcb6eb0058aa46a6be1d71447491eeec?p=ae5ebd42c61340fb8fd909df43e29940&pm=s'),
('reactO', 'https://fantastic-eggnog-5f1.notion.site/019555e229964774809ab90884c63d39?v=0647870937184f649123f651797ba688'),
('back-end node', 'https://academlo.notion.site/Grabaciones-aabf00470e494412b1c202f6bef505e5');


Insert into users(user_name,user_email,"user_password",user_age,user_cate)
values
('montaño123','jnmontano@gmail.com','12345','25','1'),
('obando321','joseobando30@gmail.com','34567','26','2'),
('sandoval567','eloysandoval10@hotmail.com','67890','28','3');


Insert into courses(cour_title,cour_descrip,cour_level,cour_teacher,cour_video)
values
('FOUNDATIONS IN HTML, CSS AND JAVASCRIPT',
'The student will obtain the necessary skills to correctly develop the visual part of a responsive website without using libraries/frameworks, as well as adding dynamic content with javascript, working collaboratively with git.',
'3','1','1'),
('FRONT-END DEVELOPMENT WITH REACT',
'The student will learn to create web applications with React JS, achieving a great interaction with the user using previous knowledge of HTML, CSS and Javascript.',
'3','2','2'),
('BACK-END NODE',
'The student will learn to build an application from the server with Node and Express from 0 to deployment on a server. She will have the ability to perform a Rest API using a',
'3','3','3');

Insert into users_courses(uscu_user,uscu_cour)
values
('1','3'),
('2','3'),
('3','3');


